# Generated by Django 4.1.5 on 2023-01-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': '1. About'},
        ),
        migrations.AlterModelOptions(
            name='certificates',
            options={'verbose_name': 'Certificates', 'verbose_name_plural': '3. Certificates'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': '4. Contacts'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Projects', 'verbose_name_plural': '2. Projects'},
        ),
        migrations.AddField(
            model_name='contact',
            name='dark_icon',
            field=models.ImageField(null=True, upload_to='contact_page', verbose_name='Dark_Icon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
