# Generated by Django 4.1.5 on 2023-01-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_about_options_alter_certificates_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catonecards',
            name='blog_link',
        ),
        migrations.RemoveField(
            model_name='catonecards',
            name='git_link',
        ),
        migrations.AddField(
            model_name='catonecards',
            name='button_one_name',
            field=models.CharField(default='Button 1', max_length=50, null=True, verbose_name='Button One'),
        ),
        migrations.AddField(
            model_name='catonecards',
            name='button_two_name',
            field=models.CharField(default='Button 2', max_length=50, null=True, verbose_name='Button two'),
        ),
        migrations.AddField(
            model_name='catonecards',
            name='link_1',
            field=models.TextField(null=True, verbose_name='Link one'),
        ),
        migrations.AddField(
            model_name='catonecards',
            name='link_2',
            field=models.TextField(null=True, verbose_name='Link two'),
        ),
    ]
